import {chromium} from '@playwright/test';import {writeFileSync} from 'node:fs';
const samples=[],cases=[],epsilons=[.001,.00001,.000001];
function seam(name,points){const start=samples.length;for(const e of epsilons)samples.push(...points(e));cases.push({name,start});}
for(const [name,x,z,l,r] of [['ceiling-left-rear',-4.5,-8,47,65],['ceiling-left-front',-4.5,7,47,74],['ceiling-right-rear',.3,-8,65,56],['ceiling-right-front',.3,7,74,56]])seam(name,e=>[[x-e,5.8,z,l],[x+e,5.8,z,r]]);
for(const [i,x] of [[9,-2.335],[10,2.335]])for(const face of [4,5])seam(`pillar-${i}-${face}`,e=>[[x-e,2.125,face===4?-3.65:-2.85,i*9+face],[x+e,2.125,face===4?-3.65:-2.85,(i+1)*9+face]]);
for(const [i,cx,r,z] of [[9,-4.67,1.78,-3.25],[10,0,1.78,-3.25],[11,4.67,1.78,-3.25],[12,0,2.1,-11.2]]){
 seam(`spring-${i}-right`,e=>[[cx+r,2.5-e,z,i*9+8],[cx+r*Math.cos(e/r),2.5+r*Math.sin(e/r),z,i*9+6]]);
 seam(`spring-${i}-left`,e=>[[cx-r*Math.cos(e/r),2.5+r*Math.sin(e/r),z,i*9+6],[cx-r,2.5-e,z,i*9+7]]);
}
const kernel=`@compute @workgroup_size(1) fn seamAudit(@builtin(global_invocation_id) gid:vec3u){let i=gid.x;if(i>=U.render.w*100u){return;}let sample=reflectionLayer[i];let sid=u32(sample.w);let h=makeHit(0.,sample.xyz,vec3f(0,1,0),vec3f(0,1,0),shapes[sid/9u],sid%9u);image[2u*i]=photonEstimate(h);image[2u*i+1u]=vec4f(integratedSky(h),1.);}`;
const inject=`if(options.seam){const m=device.createShaderModule({code:common+camera.slice(0,camera.indexOf('// Deterministic'))+${JSON.stringify(kernel)}});const p=await device.createComputePipelineAsync({layout:'auto',compute:{module:m,entryPoint:'seamAudit'}});const out=device.createBuffer({size:${samples.length*32},usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});const rb=device.createBuffer({size:${samples.length*32},usage:GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST});const positions=buffer('seam coordinates',new Float32Array(${JSON.stringify(samples.flat())}));const g=bindings(p,[[0,uniforms],[1,buffers.geometry],[2,buffers.surfaces],[3,buffers.combined],[4,out],[5,positions],[8,buffers.sky]]);const e=device.createCommandEncoder(),pass=e.beginComputePass();pass.setPipeline(p);pass.setBindGroup(0,g);pass.dispatchWorkgroups(${samples.length});pass.end();e.copyBufferToBuffer(out,0,rb,0,${samples.length*32});device.queue.submit([e.finish()]);await rb.mapAsync(GPUMapMode.READ);const values=Array.from(new Float32Array(rb.getMappedRange()));rb.unmap();rb.destroy();out.destroy();positions.destroy();return{values};}`;
for(const [name,url] of [['before',process.env.BASELINE_URL||'http://127.0.0.1:4178'],['after','http://127.0.0.1:4173']]){const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage();await p.route(u=>u.pathname==='/src/render/renderer.js',async r=>{const q=await r.fetch();await r.fulfill({response:q,body:(await q.text()).replace('async function audit(options={}) {','async function audit(options={}) {'+inject)});});await p.goto(url);await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.evaluate(()=>__POOLROOMS_V1__.configure({pause:true,freeze:true,scale:1}));await p.evaluate(()=>__POOLROOMS_V1__.renderEvidence(12,{},false));const result=await p.evaluate(()=>__POOLROOMS_V1__.audit({seam:true}));const errors=await p.evaluate(()=>__POOLROOMS_V1__.snapshot().errors);if(errors.length)throw Error(JSON.stringify(errors));if(!result.values.some(v=>v>0))throw Error('empty readback');writeFileSync(`../workroom-v1.39-evidence/${name}-continuity.json`,JSON.stringify({cases,epsilons,samples,...result}));console.log(name);}finally{await b.close()}}
