import{chromium}from'@playwright/test';import{execFileSync}from'node:child_process';import{mkdirSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';
const root='../workroom-v1.33-evidence/contact-audit';mkdirSync(root,{recursive:true});const result={};
for(const name of ['before','after']){const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage();if(name==='before')for(const file of ['body-waves.wgsl','body-waves.js','wave-simulation.js'])await p.route(u=>u.pathname==='/src/render/'+file,r=>{const raw=execFileSync('git',['show','8893209:src/render/'+file],{encoding:'utf8'});return r.fulfill({contentType:'text/javascript',body:file.endsWith('.wgsl')?'export default '+JSON.stringify(raw):raw.replace("'./body-waves.wgsl?raw'","'/src/render/body-waves.wgsl?import&raw'").replace("'./wave-simulation.wgsl?raw'","'/src/render/wave-simulation.wgsl?import&raw'")});});await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.evaluate(()=>window.__POOLROOMS_V1__.pause());
result[name]=await p.evaluate(async()=>{const{createWaveSimulation}=await import('/src/render/wave-simulation.js');const a=await navigator.gpu.requestAdapter(),d=await a.requestDevice(),s=await createWaveSimulation(d),errors=[];d.addEventListener('uncapturederror',e=>errors.push(e.error.message));const c={waterLevel:.42,waveAmplitude:0,waveForcing:false,waveSpeed:.28,bodyWakeBoost:.6,seed:7819301};let reference;const runs=[];
for(const hz of [30,60]){s.reset(c,{shapes:[]});const rows=[];for(let i=0;i<=hz*7;i++){const t=i/hz;if(i===hz)s.addWake({x:0,z:0,time:1,amplitude:.012});s.advance(t);if(i%hz===0){const q=await s.audit();let peak=0,energy=0,radius=0,norm=0,far=0,n=0;for(let z=1;z<863;z++)for(let x=1;x<447;x++){const k=(z*448+x)*4,h=q.values[k],r=Math.hypot(-7+(x+.5)/32,-17+(z+.5)/32);peak=Math.max(peak,Math.abs(h));energy+=h*h;radius+=r*h*h;const hx=(q.values[k+4]-q.values[k-4])*16,hz=(q.values[k+448*4]-q.values[k-448*4])*16;if(r>1&&r<4){far+=h*h;norm+=Math.atan(Math.hypot(hx,hz))**2;n++;}}rows.push({t,peakMM:peak*1000,energyRadiusM:radius/Math.max(1e-30,energy),farHeightRMSMM:Math.sqrt(far/n)*1000,farNormalRMSDegrees:Math.sqrt(norm/n)*180/Math.PI});if(t===4){if(hz===30)reference=q.values;else{let max=0,sum=0;for(let k=0;k<reference.length;k+=4){const e=q.values[k]-reference[k];max=Math.max(max,Math.abs(e));sum+=e*e;}rows.at(-1).rateDifference={maxMM:max*1000,rmsMM:Math.sqrt(sum/(448*864))*1000};}}}}runs.push({hz,rows});}const{createWakeTrail}=await import('/src/wake-trail.js');const walking=[];for(const speed of [.8,1.6]){const trail=createWakeTrail();s.reset({...c,waveAmplitude:.018,waveForcing:true},{shapes:[]});let before={x:-2.8,z:1,y:1.62},peak=0;const rows=[];for(let i=0;i<=450;i++){const t=i/30,actor={x:-2.8+Math.min(6.4,Math.max(0,t-3)*speed),z:1,y:1.62};const contact=trail.advance(before,actor,t,.42);if(contact)s.addWake(contact);s.setBody(actor);s.advance(t);before=actor;if(i%15===0){const q=await s.audit();let nowPeak=0;for(let k=0;k<q.values.length;k+=4)nowPeak=Math.max(nowPeak,Math.abs(q.values[k]));peak=Math.max(peak,nowPeak);rows.push({t,peakMM:nowPeak*1000});}}walking.push({speed,peakMM:peak*1000,rows});}d.destroy();return{runs,walking,errors};});assert.equal(result[name].errors.length,0);console.log(name,JSON.stringify(result[name]));}finally{await b.close()}}
writeFileSync(root+'/single-contact.json',JSON.stringify(result,null,2));
assert(result.after.walking.every(r=>r.peakMM<280),'combined height exceeds traced water bracket');
assert(result.after.runs[1].rows[4].rateDifference.maxMM<1,'contact solution depends on display rate');
assert(result.after.runs[0].rows[0].peakMM===0,'standing in unforced flat water creates a pulse');

