import {provenance} from './roam-v149-provenance.mjs';
import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';
const root=process.env.EVIDENCE_DIR||'../workroom-v1.53-evidence/energy';mkdirSync(root,{recursive:true});writeFileSync(root+'/source-snapshot.json',JSON.stringify(provenance(),null,2));
for(const mode of (process.env.CASES||'flat-production,flat-reference,wavy-production,wavy-reference').split(',')){
 const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:640,height:416}});await p.routeWebSocket(/.*/,w=>w.close());
 if(mode.startsWith('flat'))await p.route(u=>u.pathname==='/src/render/common.wgsl',r=>{const s=readFileSync('src/render/common.wgsl','utf8').replace(/if\(U\.sampling\.w==1u \|\| \(U\.state\.z==0\. && U\.body\.z==0\.\)\)|if\(U\.state\.z==0\. && U\.body\.z==0\.\)/,'if(U.body.z==0.)');return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(s)})});
 await p.route(u=>u.pathname==='/src/render/renderer.js',async r=>{const q=await r.fetch();let s=await q.text();s=s.replaceAll('GPUBufferUsage.STORAGE','(GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC)');s=s.replace('buffers.combined=device.createBuffer','buffers.energyDelta=device.createBuffer({size:geometry.totalCells*16,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});\n    buffers.combined=device.createBuffer');s=s.replace('[7,buffers.combined],[8,buffers.cellSurface]','[7,buffers.combined],[8,buffers.cellSurface],[10,buffers.energyDelta]');s=s.replace('quality=Math.max(0,Math.min(1,quality+(moving?-dt/.35:dt/.8)));','quality=1;');s=s.replace('async function audit(options={}) {','async function audit(options={}) {\nif(options.warm){for(let i=1;i<=options.warm*30;i++){simulation.advance(i/30);if(i%60===0)await device.queue.onSubmittedWorkDone();}return;}\n'+readFileSync('scripts/energy-readback-v153.txt','utf8'));await r.fulfill({response:q,body:s})});
 await p.route(u=>u.pathname==='/src/render/compose-light.wgsl',r=>{let s=readFileSync('src/render/compose-light.wgsl','utf8');s='@group(0) @binding(10) var<storage,read_write> energyDelta:array<vec4f>;\n'+s;s=s.replace('let base=mix','energyDelta[idx]=vec4f(sum/max(weight,.0001),0.);\n let base=mix');return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(s)})});
 if(mode.endsWith('reference'))await p.route(u=>u.pathname==='/src/render/photons.wgsl',r=>{let s=readFileSync('src/render/photons.wgsl','utf8');s=s.replace('if(bounce>0u && !(U.sampling.z==1u && touchedWater && diffuseBounces==0u))','if(bounce>0u)');if(mode.startsWith('wavy'))s=s.replace('if(U.sampling.z==1u){','if(U.sampling.z==999u){');return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(s)})});
 await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs,null,{timeout:180000});await p.evaluate(async mode=>{const a=__POOLROOMS_V1__;await a.configure({pause:true,freeze:false,body:false,waveAmplitude:mode.startsWith('flat')?0:.018,seed:7819301,scale:1,exposure:.85,focalLength:24});await a.audit({warm:6});await a.renderEvidence(6,{x:-3.6,y:1.62,z:8,yaw:-.29,pitch:.55},false,false)},mode);
 const energy=await p.evaluate(()=>__POOLROOMS_V1__.audit({energy:true}));if(energy.errors.length)throw Error(JSON.stringify(energy.errors));writeFileSync(`${root}/${mode}.json`,JSON.stringify(energy,null,2));const audit=await p.evaluate(()=>__POOLROOMS_V1__.audit());writeFileSync(`${root}/${mode}-paths.json`,JSON.stringify(audit));console.log(mode,energy.regions.all.fields);
 }finally{await b.close()}
}
