import{chromium}from'@playwright/test';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const root=process.env.EVIDENCE_DIR||'../workroom-v1.31-evidence';const variants=JSON.parse(process.env.VARIANTS||'["before","no-cache","no-sky","no-sun","no-bounce","wide-cache"]');
for(const name of variants){const out=root+'/'+name;mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1024,height:1024}});
await p.route(u=>u.pathname==='/src/render/renderer.js',r=>{let s=readFileSync('src/render/renderer.js','utf8').replaceAll('size:geometry.totalCells*16,usage:GPUBufferUsage.STORAGE});','size:geometry.totalCells*16,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});').replaceAll('encFloor.copyBufferToBuffer(buffers.liveField,','encFloor.copyBufferToBuffer(buffers[options.field||"liveField"],').replaceAll('e.copyBufferToBuffer(buffers.liveField,','e.copyBufferToBuffer(buffers[options.field||"liveField"],').replace('    configure,','    configure,\n    evidenceLens(p){config.focalLength=p.focalLength;config.exposure=p.exposure;},');return r.fulfill({contentType:'text/javascript',body:s})});
await p.route(u=>u.pathname==='/src/main.js',r=>r.fulfill({contentType:'text/javascript',body:readFileSync('src/main.js','utf8').replace('snapshot: () => ({','evidenceLens:p=>renderer.evidenceLens(p),\n    snapshot: () => ({')}));
for(const file of ['resolve.wgsl','compose-light.wgsl','water-caustics.wgsl'])await p.route(u=>u.pathname===`/src/render/${file}`,r=>{let s=readFileSync('src/render/'+file,'utf8');if(file==='water-caustics.wgsl'&&name!=='after'&&name!=='footprint')s=execFileSync('git',['show','58c217e:src/render/water-caustics.wgsl'],{encoding:'utf8'});if(file==='resolve.wgsl'&&name==='wide-cache')s=execFileSync('git',['show','d42d844:src/render/resolve.wgsl'],{encoding:'utf8'});if(file==='compose-light.wgsl'){if(name==='no-cache')s=s.replace('mix(coarse[idx],fine[idx],U.lighting.z)','mix(coarse[idx],fine[idx],U.lighting.z)*select(0.,1.,U.state.y<0.)');if(name==='no-bounce')s=s.replace('sum/max(weight,.0001)','sum/max(weight,.0001)*select(0.,1.,U.state.y<0.)');}if(file==='water-caustics.wgsl'){if(name==='footprint')s=readFileSync(root+'/footprint.wgsl','utf8');if(name==='no-sky')s=s.replace('if(i<nx*ny){','if(i<nx*ny && U.state.y<0.){');if(name==='no-sun')s=s.replace('if(i<nSun*nSun){','if(i<nSun*nSun && U.state.y<0.){');}return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(s)})});
await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.evaluate(name=>window.__POOLROOMS_V1__.configure({pause:true,freeze:false,body:false,grain:0,scale:1,...(name==='sky-half'?{skyGridX:128,skyGridY:256}:{})}),name);
const marks=JSON.parse(process.env.MARKS||'[6]');for(let i=0;i<=marks.at(-1)*30;i++){const t=i/30;await p.evaluate(t=>window.__POOLROOMS_V1__.renderEvidence(t,{},false,false),t);if(process.env.RECORD==='1'&&i>=180&&i<=360){
 for(const view of ['above','under']){const dir=out+'/sequence-'+view;mkdirSync(dir,{recursive:true});const pose={x:-2,y:view==='under'?.35:1.4,z:-.5,yaw:0,pitch:-Math.PI/2};await p.evaluate(lens=>window.__POOLROOMS_V1__.evidenceLens(lens),{focalLength:view==='under'?4.2:14,exposure:.85});const r=await p.evaluate(({t,pose})=>window.__POOLROOMS_V1__.renderEvidence(t,pose,false,true),{t,pose});writeFileSync(`${dir}/${String(i-180).padStart(4,'0')}.png`,Buffer.from(r.png.split(',')[1],'base64'));}
 }if(i%300===0)console.log(name,'replay',t);if(!marks.includes(t))continue;
 for(const region of ['bright','dark'])for(const view of ['above','under']){const pose={x:region==='bright'?3:-2,y:view==='under'?.35:1.4,z:-.5,yaw:0,pitch:-Math.PI/2};await p.evaluate(lens=>window.__POOLROOMS_V1__.evidenceLens(lens),{focalLength:view==='under'?4.2:14,exposure:region==='bright'?.15:.85});const f=await p.evaluate(({t,pose})=>window.__POOLROOMS_V1__.renderEvidence(t,pose,false,true),{t,pose});writeFileSync(`${out}/${region}-${view}-${t}.png`,Buffer.from(f.png.split(',')[1],'base64'));}
 for(const field of ['combined','fine0','liveField']){const a=await p.evaluate(async field=>{const q=await window.__POOLROOMS_V1__.audit({receivers:[3],field});const r=q.receivers[3],values=[];for(let z=14*48;z<20*48;z++)for(let x=3*48;x<12*48;x++){const k=(z*r.nx+x)*4;values.push(...r.irradiance.slice(k,k+4));}return{nx:432,ny:288,bounds:[-4,5,-3,3],values,errors:q.errors};},field);assert(!a.errors?.length,JSON.stringify(a.errors));writeFileSync(`${out}/${field}-${t}.f32`,Buffer.from(new Float32Array(a.values).buffer));delete a.values;writeFileSync(`${out}/meta.json`,JSON.stringify(a));}
 console.log(name,t);
 }assert.equal((await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot())).errors.length,0);
}finally{await b.close()}}
