
import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';
const width=Number(process.env.BENCH_WIDTH||1280),height=Math.round(width*832/1280);
const tuning={waveSpeed:.21,bodyWakeBoost:.6};
const out=process.env.EVIDENCE_DIR||'../workroom-v1.39-evidence/performance-default';mkdirSync(out,{recursive:true});
function stats(frames){const ms=frames.map(x=>x.ms),sorted=[...ms].sort((a,b)=>a-b);let t=0;const bins=[];for(const m of ms){(bins[Math.floor(t/1000)]??=[]).push(m);t+=m}return{fps:1000*ms.length/t,p95:sorted[Math.floor(sorted.length*.95)],max:sorted.at(-1),minOneSecond:Math.min(...bins.slice(0,-1).map(a=>1000*a.length/a.reduce((x,y)=>x+y))),over50:ms.filter(x=>x>50).length,count:ms.length}}
const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width,height}});await p.route(u=>u.pathname==='/src/main.js',async r=>{const response=await r.fetch();const body=(await response.text()).replace('if (!paused && !holdTime && frameMs.length > 60 && done - lastResize > 900)','if (false)');await r.fulfill({response,body})});await p.goto(process.env.VERIFY_URL||'http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);const first=await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot().firstFrameMs),cases=[];
for(const region of ['default'])for(const mode of ['static','slow','fast']){const view={x:-3.6,y:1.62,z:8,yaw:-.29,pitch:-.32};await p.evaluate(({view,tuning})=>{const a=window.__POOLROOMS_V1__;a.setObserver(null);return a.configure({view,...tuning,pause:false,freeze:false,scale:1})},{view,tuning});await p.waitForTimeout(2500);const start=await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot().elapsed);if(mode==='fast')await p.keyboard.down('ShiftLeft');if(mode==='static')await p.waitForTimeout(6000);else for(let i=0;i<6;i++){const k=i%2?'KeyS':'KeyW';await p.keyboard.down(k);await p.waitForTimeout(1000);await p.keyboard.up(k);}await p.keyboard.up('ShiftLeft');const s=await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot());const r={region,mode,...stats(s.frames.filter(f=>f.t>start+.5)),resolution:s.internal,errors:s.errors,packets:{sun:s.dynamics.sunPackets,sky:s.dynamics.skyPackets}};cases.push(r);console.log(r);assert.equal(s.errors.length,0);assert.deepEqual(s.internal,[Math.round(width/8)*8,Math.round(height/8)*8]);}
writeFileSync(`${out}/performance.json`,JSON.stringify({tuning,firstFrameMs:first,cases},null,2));assert(first<3000);assert(cases.every(r=>r.fps>=30&&r.minOneSecond>=30));
}finally{await b.close()}
