import {chromium} from '@playwright/test';import {mkdirSync,writeFileSync,copyFileSync} from 'node:fs';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'../workroom-v1.22-evidence/final';mkdirSync(`${out}/frames`,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});
try {const c=await b.newContext({viewport:{width:1280,height:832},recordVideo:{dir:`${out}/browser`,size:{width:1280,height:832}}});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);
const view={x:3.5,y:1.5,z:-1,yaw:0,pitch:-Math.PI/2};
await p.evaluate(view=>window.__POOLROOMS_V1__.configure({view,body:false,pause:false,freeze:false,grain:.004,scale:1}),view);await p.evaluate(()=>document.body.classList.add('evidence'));
const marks=[];const start=Date.now();for(let i=0;i<=24;i++){await p.waitForTimeout(Math.max(0,start+i*1000-Date.now()));const r=await p.evaluate(()=>({s:window.__POOLROOMS_V1__.snapshot(),png:document.querySelector('canvas').toDataURL()}));writeFileSync(`${out}/realtime-${String(i).padStart(2,'0')}.png`,Buffer.from(r.png.split(',')[1],'base64'));marks.push({second:i,elapsed:r.s.elapsed,frames:r.s.completedFrames,view:r.s.view,internal:r.s.internal});}
await p.evaluate(()=>window.__POOLROOMS_V1__.pause());const video=p.video();await c.close();copyFileSync(await video.path(),`${out}/floor-fixed-realtime.webm`);
const q=await b.newPage({viewport:{width:1280,height:832}});await q.goto('http://localhost:4173');await q.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await q.evaluate(view=>window.__POOLROOMS_V1__.configure({view,body:false,pause:true,freeze:false,grain:.004,scale:1}),view);
for(let i=0;i<600;i++){const r=await q.evaluate(i=>window.__POOLROOMS_V1__.renderEvidence(i/30,{},false,true),i);writeFileSync(`${out}/frames/frame-${String(i).padStart(4,'0')}.png`,Buffer.from(r.png.split(',')[1],'base64'));if(i%60===0)console.log('frame',i);}
const final=await q.evaluate(()=>window.__POOLROOMS_V1__.snapshot());writeFileSync(`${out}/record.json`,JSON.stringify({realtime:'24 seconds browser recording, fixed camera; includes video overhead. Not the performance benchmark.',sequence:'600 GPU-completed frames replayed from reset at 30Hz, for lossless visual inspection. Not realtime fps.',marks,errors:[...errors,...final.errors],config:final.config},null,2));assert.equal(errors.length+final.errors.length,0);
}finally{await b.close()}
