import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,copyFileSync}from'node:fs';import assert from'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'../workroom-v1.13-evidence/final';mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});
try{const context=await b.newContext({viewport:{width:1512,height:982},recordVideo:{dir:`${out}/raw-video`,size:{width:1512,height:982}}});const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.keyboard.press('Space');
const view={x:3,y:1.62,z:1,yaw:0,pitch:-1.05};await p.evaluate(async view=>{await window.__POOLROOMS_V1__.configure({view,grain:.004,freeze:false,pause:false,scale:1280/1512});document.body.classList.add('evidence');window.walkLog=[];window.walkTimer=setInterval(()=>{const s=window.__POOLROOMS_V1__.snapshot();window.walkLog.push({view:s.view,t:s.elapsed,wakes:s.wakes,dynamics:s.dynamics,internal:s.internal,completed:s.completedFrames})},100)},view);
const marks=[];async function segment(name,key,ms){marks.push({name,key,at:await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot().elapsed),duration:ms});if(key)await p.keyboard.down(key);await p.waitForTimeout(ms);if(key)await p.keyboard.up(key)}
async function capture(name){const r=await p.evaluate(()=>({png:document.querySelector('canvas').toDataURL('image/png'),state:window.__POOLROOMS_V1__.snapshot()}));writeFileSync(`${out}/${name}.png`,Buffer.from(r.png.split(',')[1],'base64'));delete r.png;delete r.state.frames;writeFileSync(`${out}/${name}.json`,JSON.stringify(r,null,2));}
await segment('stationary observation',null,6000);await capture('same-area-early');
await segment('walking forward','KeyW',2000);await segment('walking right','KeyD',1500);await segment('walking back','KeyS',2000);await segment('walking left','KeyA',1500);await capture('walking-floor');
// A smooth camera-only crouch and tilt; actual foot contacts above all came
// through collision-resolved keyboard motion. Crouching does not inject energy.
const before=await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot().view);for(let i=1;i<=30;i++){await p.evaluate(({before,k})=>window.__POOLROOMS_V1__.setView({y:before.y+(.72-before.y)*k,pitch:before.pitch+(-.12-before.pitch)*k}),{before,k:i/30});await p.waitForTimeout(20);}
await segment('close water reflection',null,6500);await capture('water-close');
await p.evaluate(view=>window.__POOLROOMS_V1__.setView(view),view);await segment('same region later',null,6000);await capture('same-area-late');
const result=await p.evaluate(()=>{clearInterval(window.walkTimer);return{log:window.walkLog,snapshot:window.__POOLROOMS_V1__.snapshot()}});const video=p.video();await context.close();copyFileSync(await video.path(),`${out}/walking-waves.webm`);const contacts=new Map(result.log.flatMap(x=>x.wakes).map(x=>[x.time,x]));writeFileSync(`${out}/walking.json`,JSON.stringify({method:'Actual wall-clock browser video, no frame synthesis or time remapping; keyboard through collision-resolved locomotion, smooth camera crouch. Grain .004; recording overhead not benchmark FPS.',marks,contacts:[...contacts.values()],errors,...result},null,2));assert(contacts.size>=8);assert.equal(errors.length,0);console.log({contacts:contacts.size,first:result.snapshot.firstFrameMs,resolution:result.snapshot.internal,duration:result.log.at(-1).t-result.log[0].t,errors});}finally{await b.close()}
