// Matched 66–72s Benchmark wall/ceiling replay: roll back one transport setting at a time.
import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,readFileSync,existsSync}from'node:fs';import{spawn}from'node:child_process';import{once}from'node:events';import{sample}from'./roam-v149-path.mjs';
for(const variant of (process.env.CASES||'current,photons-1x,sky-64,diffuse-32,sun-point,all-four,flux-24,no-reflected-water,flat-interface,no-sun-water,no-sky-water,water-sky-64,no-diffuse,static-light,no-glaze,no-cache,cache-seed,cache-4x-batches,flat-ceiling-albedo,all-four-no-reflected-water').split(',')){const sunGrid=384;const out=`${process.env.AB_ROOT||'../workroom-v1.51-evidence/ab'}/${variant}`;if(existsSync(out+'/snapshot.json'))throw Error('Completed evidence exists; set AB_ROOT to a fresh folder: '+out);mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});let enc;
try{const p=await b.newPage({viewport:{width:640,height:416}});await p.routeWebSocket(/.*/,w=>w.close());
const rollback=(name)=>variant===name||variant.startsWith('all-four');
const edit=(file,fn)=>p.route(u=>u.pathname===`/src/render/${file}`,r=>{const s=fn(readFileSync(`src/render/${file}`,'utf8'));return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(s)})});
if(variant==='cache-seed')await edit('photons.wgsl',s=>s.replace('U.counts.w);','(U.counts.w+123457u));'));
if(variant==='flat-ceiling-albedo')await p.route(u=>u.pathname==='/materials/porcelain.wgsl',r=>r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(readFileSync('materials/porcelain.wgsl','utf8').replace('*(.86+.14*noise(uv*.61))','*.93').replace('*(.86+.14*fbm(uv*.61))','*.93'))}));
if(variant==='no-cache')await edit('compose-light.wgsl',s=>s.replace('mix(coarse[idx],fine[idx],U.lighting.z)','mix(coarse[idx],fine[idx],U.lighting.z)*select(0.,1.,U.settings.w>10.)'));
if(['no-diffuse','static-light'].includes(variant))await edit('compose-light.wgsl',s=>{s=s.replace('base.rgb+sum/max(weight,.0001)','base.rgb');if(variant==='static-light')s=s.replace('+water[idx]','+water[idx]*select(0.,1.,U.settings.w>10.)');return s;});
if(variant==='no-glaze')await edit('camera.wgsl',s=>s.replace('if(m.coat>.009){','if(false){'));
if(rollback('sky-64'))await edit('sky.wgsl',s=>s.replaceAll('256','64').replaceAll('16','8'));
if(rollback('diffuse-32'))await edit('diffuse-transfer.wgsl',s=>s.replace('DIFFUSE_DIRECTIONS:u32=128u','DIFFUSE_DIRECTIONS:u32=32u'));
if(rollback('sun-point')||variant==='flux-24'||['no-reflected-water','all-four-no-reflected-water','flat-interface','no-sun-water','no-sky-water','water-sky-64'].includes(variant))await edit('water-caustics.wgsl',s=>{
 if(rollback('sun-point'))s=s.replace('solarDiskDirection(k)','sunDirection()').replace('solarDiskDirection(k+2u)','sunDirection()');
 if(variant==='flux-24')s=s.replace('1073741824.','16777216.');
 if(variant.endsWith('no-reflected-water'))s=s.replace('for(var branch=0u;branch<2u;branch++)','for(var branch=1u;branch<2u;branch++)');
 if(variant==='flat-interface')s=s.replaceAll('let w=wave(xz);','let w=select(vec3f(U.state.y,0.,0.),wave(xz),U.settings.w>10.);');
 if(variant==='no-sun-water')s=s.replace('if(i<nSun*nSun){','if(false){');
 if(variant==='no-sky-water')s=s.replace('if(i<nx*ny){','if(false){');
 if(variant==='water-sky-64')s=s.replace('for(var k=0u;k<4u;k++)','for(var k=0u;k<64u;k++)').replace('let uv=vec2f(.25+f32(k%2u)*.5,.25+f32(k/2u)*.5);','let uv=(vec2f(f32(k%8u),f32(k/8u))+.5)/8.;').replace('lightArea/(4.*d*d)','lightArea/(64.*d*d)');
 return s;
});
await p.route(u=>u.pathname==='/src/main.js',async r=>{const q=await r.fetch();let s=await q.text();s=s.replace('camera,capture=true){','camera,capture=true,moving=true){').replace('renderer.render(camera,time,true,1)','renderer.render(camera,time,moving,1)');s=s.replace('audit: (options) => renderer.audit(options),',`async warmActors(rows){for(const {t,actor} of rows){const before={...view};Object.assign(view,actor);const w=wakeTrail.advance(before,view,t,renderer.config.waterLevel);if(w)renderer.addWake(w);renderer.setBody(view);await renderer.audit({advanceOnly:t});}},audit: (options) => renderer.audit(options),`);await r.fulfill({response:q,body:s})});await p.route(u=>u.pathname==='/src/render/renderer.js',async r=>{const q=await r.fetch();let s=await q.text();if(variant==='cache-4x-batches')s=s.replace('config.freeze?lightBatches():128','config.freeze?lightBatches():512').replace('batch===128','batch===512');s=s.replace('async function audit(options={}) {','async function audit(options={}) {if(options.advanceOnly!==undefined){simulation.advance(options.advanceOnly);return;}');await r.fulfill({response:q,body:s})});await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs,null,{timeout:120000});await p.evaluate(async({sunGrid,state,photonCount})=>{document.body.classList.add('evidence');const a=__POOLROOMS_V1__;await a.configure({view:state.actor,seed:7819301,pause:true,freeze:false,scale:1,grain:.004,body:true,focalLength:24,sunGrid,photonCount});await a.renderActorEvidence(0,state.actor,state.camera,false,false)},{sunGrid,state:sample(0),photonCount:rollback('photons-1x')?49152:196608});
for(let i=1;i<=1980;i+=60)await p.evaluate(rows=>__POOLROOMS_V1__.warmActors(rows),Array.from({length:Math.min(60,1981-i)},(_,j)=>({t:(i+j)/30,actor:sample((i+j)/30).actor})));
enc=spawn(process.env.PYTHON||'/opt/homebrew/bin/python3',['scripts/roam-v149-encode.py',out,'180','640','416','30'],{stdio:['pipe','inherit','inherit']});const done=once(enc,'exit');
for(let i=0;i<180;i++){const t=66+i/30,state=sample(t);const q=await p.evaluate(async({t,state})=>{const a=__POOLROOMS_V1__,q=await a.renderActorEvidence(t,state.actor,state.camera,true,false);return{png:q.png,errors:a.snapshot().errors}},{t,state});if(q.errors.length)throw Error(JSON.stringify(q.errors));const d=Buffer.from(q.png.split(',')[1],'base64'),h=Buffer.alloc(4);h.writeUInt32LE(d.length);if(!enc.stdin.write(Buffer.concat([h,d])))await once(enc.stdin,'drain');}enc.stdin.end();if((await done)[0]!==0)throw Error('encode');writeFileSync(out+'/snapshot.json',JSON.stringify(await p.evaluate(()=>__POOLROOMS_V1__.snapshot()),null,2));console.log('rollback control',variant);
}finally{enc?.stdin.destroy();if(enc?.exitCode===null)enc.kill();await b.close()}}
