import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,existsSync}from'node:fs';import{spawnSync}from'node:child_process';import assert from'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'../workroom-v1.16-evidence/final';const ff='/Users/steven/Library/Caches/ms-playwright/ffmpeg-1011/ffmpeg-mac';mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});
try{const p=await b.newPage({viewport:{width:1280,height:832}});await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);const camera={x:1,y:5.65,z:3.1,yaw:0,pitch:-1.2};
for(const[name,speed]of[['slow',.8],['fast',1.6]]){const dir=`${out}/${name}-lossless-frames`;mkdirSync(dir,{recursive:true});await p.evaluate(async()=>{await window.__POOLROOMS_V1__.configure({pause:true,freeze:false,view:{x:-2,y:1.62,z:1,yaw:-Math.PI/2,pitch:-.8},scale:1,grain:.004});document.body.classList.add('evidence')});const states=[];if(!process.env.RESUME||!existsSync(`${out}/${name}-sequence.json`)){
for(let i=0;i<=600;i++){const t=i/30,actor={x:-2+Math.min(5.6,Math.max(0,t-3)*speed),z:1};const r=await p.evaluate(({t,actor,camera})=>window.__POOLROOMS_V1__.renderActorEvidence(t,actor,camera,true),{t,actor,camera});writeFileSync(`${dir}/frame-${String(i).padStart(4,'0')}.png`,Buffer.from(r.png.split(',')[1],'base64'));assert.equal(r.dynamics.waveTime,r.dynamics.causticTime);if(i%30===0)states.push({t,actor,simulation:r.dynamics.simulation});}
const errors=await p.evaluate(()=>window.__POOLROOMS_V1__.snapshot().errors);assert.equal(errors.length,0);writeFileSync(`${out}/${name}-sequence.json`,JSON.stringify({method:'601 consecutive production renderer PNG frames, physical time at30Hz,20seconds. Includes standing, real body/footstep source progression,5.6m straight walk,stop and continued evolution. This is deterministic replay, not real-time performance. Original keyboard-driven browser recordings are supplied separately.',camera,speed,states,errors},null,2));console.log(name,'captured');}
const encoded=spawnSync('/opt/homebrew/bin/python',['scripts/encode-v116.py',dir,`${out}/high-angle-${name}-hq.webm`],{encoding:'utf8'});assert.equal(encoded.status,0,encoded.stderr);console.log(name,'encoded');
}
}finally{await b.close()}
