import{createHash}from'node:crypto';
import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';
const root='../workroom-v1.43-evidence',name=process.env.VARIANT||'before',out=`${root}/${process.env.HOT?"hot":"wall"}-${name}`;mkdirSync(out,{recursive:true});
let source=readFileSync(name==='before'||name==='dense'||name==='receiver48'?'../workroom-v1.43-evidence/baseline-water-caustics.wgsl':(name.startsWith('reference')||['interleaved','paired','four-ray'].includes(name))?'../workroom-v1.43-evidence/four-ray-water-caustics.wgsl':'src/render/water-caustics.wgsl','utf8');
if(name==='paired')source=source.replace('for(var k=0u;k<SUN_SAMPLES;k++){solarWaterPacket(i,nSun,solarDiskDirection(k));}', 'let k=(i%nSun+i/nSun)%2u;solarWaterPacket(i,nSun,solarDiskDirection(k));solarWaterPacket(i,nSun,solarDiskDirection(k+2u));').replace('nSun*nSun*SUN_SAMPLES','nSun*nSun*2u');
if(name==='interleaved')source=source.replace('for(var k=0u;k<SUN_SAMPLES;k++){solarWaterPacket(i,nSun,solarDiskDirection(k));}', 'let k=(i%nSun)%2u+2u*((i/nSun)%2u);solarWaterPacket(i,nSun,solarDiskDirection(k));').replace('nSun*nSun*SUN_SAMPLES','nSun*nSun');
if(name.startsWith('reference'))source=source.replace('SUN_SAMPLES:u32=4u','SUN_SAMPLES:u32='+name.slice(9)+'u');
if(name==='no-sun')source=source.replace('if(i<nSun*nSun)','if(false)');
if(name==='receiver48')source=source.replaceAll('let radius=select(3,1,s.metric.w>4.);','let radius=select(select(3,1,s.metric.w>4.),7,(cellSurface[idx]&65535u)==18u);').replace('var x=-3;x<=3','var x=-7;x<=7').replace('var y=-3;y<=3','var y=-7;y<=7');
const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:832}});await p.route(u=>u.pathname==='/src/render/water-caustics.wgsl',r=>r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(source)}));if(name==='flat')await p.route(u=>u.pathname==='/src/render/common.wgsl',r=>r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(readFileSync('src/render/common.wgsl','utf8').replace('if(U.state.z==0. && U.body.z==0.)','if(U.state.y>0.)'))}));await p.route(u=>u.pathname==='/src/render/renderer.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('Math.min(768,','Math.min(1536,').replace('usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});\n    buffers.liveField','usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC});\n    buffers.liveField').replace('async function audit(options={}) {',`async function audit(options={}) {if(options.flux){const size=geometry.totalCells*16;const rb=device.createBuffer({size,usage:GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST});const e=device.createCommandEncoder();e.copyBufferToBuffer(buffers.liveFlux,0,rb,0,size);device.queue.submit([e.finish()]);await rb.mapAsync(GPUMapMode.READ);const a=new Uint32Array(rb.getMappedRange());let max=0,sum=0;for(let i=0;i<a.length;i++){max=Math.max(max,a[i]);sum+=a[i];}rb.unmap();rb.destroy();return{maxUint:max,fractionOfUint32:max/4294967295,sumUint:sum}};`)})});if(name==='receiver48')await p.route(u=>u.pathname==='/src/render/light-atlas.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('faces.push({sid:', 'if(i===2&&face===0)density=48;faces.push({sid:').replace('totalCells+=g.nx*g.ny','if(g.members.some(m=>m.sid===18))g.stride=8;totalCells+=g.nx*g.ny')})});await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.evaluate(({name})=>{document.body.classList.add('evidence');return __POOLROOMS_V1__.configure({view:{x:4,y:1.62,z:-1.5,yaw:-Math.PI/2,pitch:.55},focalLength:24,body:false,grain:0,pause:true,freeze:false,scale:1,sunGrid:name==='dense'?768:name==='ultra'?1536:384})},{name});
for(let i=0;i<=180;i++)await p.evaluate(t=>__POOLROOMS_V1__.renderEvidence(t,{},false,false),i/30);
for(let i=0;i<(Number(process.env.FRAMES)||61);i++){const t=6+i/30,q=await p.evaluate(t=>__POOLROOMS_V1__.renderEvidence(t,{},false),t);writeFileSync(`${out}/${String(i).padStart(3,'0')}.png`,Buffer.from(q.png.split(',')[1],'base64'));const a=await p.evaluate(()=>__POOLROOMS_V1__.audit({receivers:[18]}));const field=a.receivers[18];writeFileSync(`${out}/${String(i).padStart(3,'0')}.f32`,Buffer.from(new Float32Array(field.irradiance).buffer));if(i===0)writeFileSync(out+'/field.json',JSON.stringify({nx:field.nx,ny:field.ny}));}
const lastIndex=(Number(process.env.FRAMES)||61)-1;const again=await p.evaluate(t=>__POOLROOMS_V1__.renderEvidence(t,{},false),6+lastIndex/30);const lastPNG=readFileSync(`${out}/${String(lastIndex).padStart(3,'0')}.png`);const repeatPNG=Buffer.from(again.png.split(',')[1],'base64');const hashes=[lastPNG,repeatPNG].map(x=>createHash('sha256').update(x).digest('hex'));writeFileSync(out+'/same-time.json',JSON.stringify({time:6+lastIndex/30,hashes,identical:hashes[0]===hashes[1]},null,2));writeFileSync(out+'/flux.json',JSON.stringify(await p.evaluate(()=>__POOLROOMS_V1__.audit({flux:true})),null,2));writeFileSync(out+'/snapshot.json',JSON.stringify(await p.evaluate(()=>__POOLROOMS_V1__.snapshot()),null,2));console.log(name);await p.close();}finally{await b.close()}
