import{chromium}from'@playwright/test';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';import{installBaseline}from'./baseline-v145.mjs';
const name=process.env.VARIANT||'after',start=Number(process.env.START||6),out=`../workroom-v1.45-evidence/wall-${name}-${start}`;mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:832}});await installBaseline(p,name);await p.route(u=>u.pathname==='/src/render/compose-light.wgsl',r=>{const s=readFileSync('src/render/compose-light.wgsl','utf8').replace(')),base.w)', ')),base.w)');const body=s.replace('base.w);','min(min((base.rgb+sum/max(weight,.0001)).r,(base.rgb+sum/max(weight,.0001)).g),(base.rgb+sum/max(weight,.0001)).b));');return r.fulfill({contentType:'text/javascript',body:'export default '+JSON.stringify(body)})});
await p.route(u=>u.pathname==='/src/render/renderer.js',async r=>{const q=await r.fetch();let s=await q.text();s=s.replace('buffers.combined=device.createBuffer({size:geometry.totalCells*16,usage:GPUBufferUsage.STORAGE});','buffers.combined=device.createBuffer({size:geometry.totalCells*16,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});');s=s.replace('async function audit(options={}) {',`async function audit(options={}) {
if(options.warm){for(let i=1;i<=options.warm*30;i++){simulation.advance(i/30);if(i%60===0)await device.queue.onSubmittedWorkDone();}return simulation.info;}
let composition=null;if(options.composition){const size=geometry.totalCells*16;const rb=device.createBuffer({size,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const e=device.createCommandEncoder();e.copyBufferToBuffer(buffers.combined,0,rb,0,size);device.queue.submit([e.finish()]);await rb.mapAsync(GPUMapMode.READ);const f=new Float32Array(rb.getMappedRange());let negative=0,min=Infinity;const bySid={};for(let i=3;i<f.length;i+=4){if(f[i]<0){negative++;const packed=geometry.cellSurfaces[(i-3)/4];if(packed>>16){const sid=packed&65535;if(!bySid[sid])bySid[sid]={count:0,min:0};bySid[sid].count++;bySid[sid].min=Math.min(bySid[sid].min,f[i]);}}min=Math.min(min,f[i]);}composition={negative,min,bySid};rb.unmap();rb.destroy();}
`);s=s.replace('return {\n      simulation:', 'return {composition,\n      simulation:');await r.fulfill({response:q,body:s})});
await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__POOLROOMS_V1__?.snapshot().firstFrameMs);await p.evaluate(()=>{document.body.classList.add('evidence');return __POOLROOMS_V1__.configure({view:{x:4,y:1.62,z:-1.5,yaw:-Math.PI/2,pitch:.55},focalLength:24,body:false,grain:0,pause:true,freeze:false,scale:1})});
await p.evaluate(()=>__POOLROOMS_V1__.renderEvidence(0,{},false,false));await p.evaluate(t=>__POOLROOMS_V1__.audit({warm:t}),start);const flags=[];
for(let i=0;i<Number(process.env.FRAMES||241);i++){const t=start+i/30,q=await p.evaluate(({t,capture})=>__POOLROOMS_V1__.renderEvidence(t,{},false,capture),{t,capture:i%30===0});if(q.png)writeFileSync(`${out}/${String(i).padStart(3,'0')}.png`,Buffer.from(q.png.split(',')[1],'base64'));const field=await p.evaluate(async()=>{const q=await __POOLROOMS_V1__.audit({receivers:[18],composition:true}),f=q.receivers[18],u=new Uint8Array(new Float32Array(f.irradiance).buffer);let s='';for(let k=0;k<u.length;k+=8192)s+=String.fromCharCode(...u.subarray(k,k+8192));return {nx:f.nx,ny:f.ny,raw:btoa(s),composition:q.composition}});flags.push({t,...field.composition});writeFileSync(`${out}/${String(i).padStart(3,'0')}.f32`,Buffer.from(field.raw,'base64'));if(i===0)writeFileSync(out+'/field.json',JSON.stringify({nx:field.nx,ny:field.ny}));if(i%60===0)console.log(name,t);}
writeFileSync(out+'/composition.json',JSON.stringify(flags));writeFileSync(out+'/snapshot.json',JSON.stringify(await p.evaluate(()=>__POOLROOMS_V1__.snapshot()),null,2));}finally{await b.close()}
